# https://blog.travis-ci.com/2018-10-11-windows-early-release
# https://docs.travis-ci.com/user/reference/windows
# https://chocolatey.org/packages/python
os: windows   # Windows Server, version 1803
language: sh  # 'language: python' is not yet supported

py27-steps: &py27-steps
  env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
  before_install:
    - choco install python2
    - python -m pip install --upgrade pip

py35-steps: &py35-steps
  env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
  before_install:
    - choco install python --version 3.5.4
    - python -m pip install --upgrade pip

py36-steps: &py36-steps
  env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
  before_install:
    - choco install python --version 3.6.8
    - python -m pip install --upgrade pip

py37-steps: &py37-steps
  env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  before_install:
    - choco install python
    - python -m pip install --upgrade pip

matrix:
  allow_failures:
    - python: "Python 2.7"  # It is legacy Python after all...
  include:
    - name: "Python 2.7"
      <<: *py27-steps
    - name: "Python 3.5"
      <<: *py35-steps
    - name: "Python 3.6"
      <<: *py36-steps
    - name: "Python 3.7"
      <<: *py37-steps
install:
  #- pip install -r requirements.txt
  - pip install flake8  # pytest  # add other testing frameworks later
script:
  - PYVER="import sys ; print('py{}{}'.format(*sys.version_info))"
  - python setup_rat.py --yes
  # - TOXENV=${TOXENV:-$(python -c "$PYVER")}  # Longwinded...
  # - TOXENV=${TOXENV:-"py$(echo $TRAVIS_JOB_NAME | tr -d -c 0-9)"}  # Sensitive to 'name:'
  # - TOXENV=${TOXENV:-"py$(echo $TRAVIS_PYTHON_VERSION | tr -d -c 0-9)"}  # Linux only
  # - echo "TOXENV is $TOXENV"
  # - flake8 --version
  # - echo stop the build if there are Python syntax errors or undefined names
  # - echo ; echo -n "flake8 testing on " ; python --version
  # - flake8 . --count --select=E9,F401,F63,F72,F82 --show-source --statistics
  # - echo exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  # - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  # - true  # pytest --capture=sys
